"""Seeded semantic-case generators for hardened v2 (hardening §6).

Each profile generates a deterministic pytest file from a seed drawn AFTER the
agent finishes; the seed, generator version, and suite hash are recorded in
evidence, and ``grader-v2 replay`` regenerates the identical file.

Mechanisms used (at least two per task, hardening §6 minimum):
- randomized hidden inputs: a seeded RNG draws id batches / argument shapes
  that the fixed authoritative examples never enumerate;
- input-shape expansion: list, tuple, generator, iterator, custom iterable,
  empty, duplicates, nested containers, boundary values;
- state-transition checks: persistence across storage reload, idempotence,
  update-then-remove sequences;
- metamorphic properties: equal arguments hash equal, results agree with
  ``get(doc_ids=...)``, untouched documents keep their state;
- differential testing: query results compared against direct predicate
  application (the documented contract), not against any one fixed answer.

The generated expectations are derived from the task contracts in
``tasks/<id>/prompt.md`` at generation time, never from the workspace code.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import cast

_HEADER_DOCIDS = '''\
"""Generated by grader_v2 semantic profile tinydb-docids-v1 (seed={seed}).
Regenerate with: grader-v2 replay --task tinydb-missing-doc-ids --seed {seed}
"""
from tinydb import TinyDB, where
from tinydb.storages import JSONStorage, MemoryStorage
from tinydb.table import Document
'''

_HEADER_QUERIES = '''\
"""Generated by grader_v2 semantic profile tinydb-query-freeze-v1 (seed={seed}).
Regenerate with: grader-v2 replay --task tinydb-query-test-unhashable --seed {seed}
"""
from tinydb.queries import Query, where
'''


@dataclass(frozen=True)
class GeneratedSuite:
    """A deterministic generated semantic suite for one profile and seed."""

    filename: str
    text: str
    expected_nodeids: list[str]


def _nodeid(filename: str, func: str) -> str:
    return f"{filename}::{func}"


def _expect_returned(requested: list[int], existing: set[int]) -> list[int]:
    """Contract: update/remove return the requested ids that existed, in order."""
    return [doc_id for doc_id in requested if doc_id in existing]


def _assert_against_count(body: str, returned: list[int]) -> str:
    """Assert update state: updated docs carry int=9; the doc that started
    with int=10 (doc id 1) keeps it only when it was not requested."""
    return (
        body
        + f"    assert db.count(where('int') == 9) == len({returned!r})\n"
        + f"    assert db.count(where('int') == 10) == ({0 if 1 in returned else 1})\n"
    )


def generate_docids_suite(seed: int) -> GeneratedSuite:
    """Generate the tinydb-missing-doc-ids semantic suite (profile v1)."""
    rng = random.Random(seed)
    existing = {1, 2, 3}

    def missing_batch(n: int) -> list[int]:
        return rng.sample(range(50, 250), n)

    def seed_mix(max_extra: int) -> tuple[list[int], list[int]]:
        existing_ids = rng.sample(sorted(existing), rng.randint(1, 3))
        missing_ids = missing_batch(rng.randint(1, max_extra))
        requested = existing_ids + missing_ids
        rng.shuffle(requested)
        return requested, missing_ids

    lines: list[str] = []
    expected: list[str] = []

    def add_case(name: str, body: str, params: str = "") -> None:
        lines.append(f"def {name}({params}):\n{body}\n")
        expected.append(_nodeid("test_semantic_docids.py", name))

    # --- input-shape expansion: tuple / generator / iterator
    for label, wrapper in (
        ("tuple", "tuple(requested)"),
        ("generator", "(i for i in requested)"),
        ("iterator", "iter(requested)"),
    ):
        requested, _ = seed_mix(3)
        returned = _expect_returned(requested, existing)
        body = (
            "    db = TinyDB(storage=MemoryStorage)\n"
            "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
            f"    requested = {requested!r}\n"
            f"    ids = {wrapper}\n"
            f"    assert sorted(db.update({{'int': 9}}, doc_ids=ids)) == sorted({returned!r})\n"
        )
        body = _assert_against_count(body, returned)
        add_case(f"test_sem_update_{label}_mixed", body)
        body = (
            "    db = TinyDB(storage=MemoryStorage)\n"
            "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
            f"    requested = {requested!r}\n"
            f"    ids = {wrapper}\n"
            f"    assert sorted(db.remove(doc_ids=ids)) == sorted({returned!r})\n"
            f"    assert len(db) == 3 - len({returned!r})\n"
        )
        add_case(f"test_sem_remove_{label}_mixed", body)

    # --- custom iterable class (not a generator, not a list)
    requested, _ = seed_mix(2)
    returned = _expect_returned(requested, existing)
    body = (
        "    class _Ids:\n"
        "        def __init__(self, items):\n"
        "            self._items = items\n"
        "        def __iter__(self):\n"
        "            return iter(self._items)\n"
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    requested = {requested!r}\n"
        "    got = sorted(db.update({'int': 9}, doc_ids=_Ids(requested)))\n"
        f"    assert got == sorted({returned!r}), (requested, got)\n"
    )
    body = _assert_against_count(body, returned)
    add_case("test_sem_update_custom_iterable_mixed", body)
    body = (
        "    class _Ids:\n"
        "        def __init__(self, items):\n"
        "            self._items = items\n"
        "        def __iter__(self):\n"
        "            return iter(self._items)\n"
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    requested = {requested!r}\n"
        "    got = sorted(db.remove(doc_ids=_Ids(requested)))\n"
        f"    assert got == sorted({returned!r}), (requested, got)\n"
        f"    assert len(db) == 3 - len({returned!r})\n"
    )
    add_case("test_sem_remove_custom_iterable_mixed", body)

    # --- empty inputs (must behave like lists, per the contract)
    add_case(
        "test_sem_update_empty_forms",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        "    assert db.update({'int': 9}, doc_ids=[]) == []\n"
        "    assert db.update({'int': 9}, doc_ids=()) == []\n"
        "    assert db.update({'int': 9}, doc_ids=(i for i in ())) == []\n"
        "    assert len(db) == 3\n",
    )
    add_case(
        "test_sem_remove_empty_forms",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        "    assert db.remove(doc_ids=[]) == []\n"
        "    assert db.remove(doc_ids=()) == []\n"
        "    assert db.remove(doc_ids=(i for i in ())) == []\n"
        "    assert len(db) == 3\n",
    )

    # --- randomized hidden inputs: only-missing batches (no KeyError, no mutation)
    missing_a = missing_batch(6)
    missing_b = missing_batch(6)
    add_case(
        "test_sem_update_only_missing_random",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    missing_a = {missing_a!r}\n"
        f"    missing_b = {missing_b!r}\n"
        "    assert db.update({'int': 9}, doc_ids=missing_a) == []\n"
        "    assert db.update({'int': 9}, doc_ids=(i for i in missing_b)) == []\n"
        "    assert db.count(where('int') == 9) == 0\n"
        "    assert len(db) == 3\n",
    )
    add_case(
        "test_sem_remove_only_missing_random",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    missing_a = {missing_a!r}\n"
        f"    missing_b = {missing_b!r}\n"
        "    assert db.remove(doc_ids=missing_a) == []\n"
        "    assert db.remove(doc_ids=(i for i in missing_b)) == []\n"
        "    assert len(db) == 3\n",
    )

    # --- randomized hidden inputs: seeded mixed batches (data-driven)
    batches: list[tuple[list[int], list[int]]] = []
    for _ in range(8):
        requested, _ = seed_mix(4)
        batches.append((requested, _expect_returned(requested, existing)))
    add_case(
        "test_sem_randomized_batches_roundtrip",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    batches = {batches!r}\n"
        "    for index, (requested, expected) in enumerate(batches):\n"
        "        if index % 3 == 0:\n"
        "            ids = tuple(requested)\n"
        "        elif index % 3 == 1:\n"
        "            ids = (i for i in requested)\n"
        "        else:\n"
        "            ids = requested\n"
        "        got = sorted(db.update({'int': 9}, doc_ids=ids))\n"
        "        assert got == sorted(expected), (requested, got, expected)\n"
        "        assert db.count(where('int') == 9) == len(expected), requested\n"
        "        db.truncate()\n"
        "        db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        "    assert len(db) == 3\n",
    )

    # --- state-transition: atomicity survives reload (JSON storage)
    requested, _ = seed_mix(3)
    returned = _expect_returned(requested, existing)
    add_case(
        "test_sem_atomicity_survives_reload",
        "    db = TinyDB(tmp_path / 'db.json', storage=JSONStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    requested = {requested!r}\n"
        f"    expected = {returned!r}\n"
        "    got = sorted(db.update({'int': 9}, doc_ids=requested))\n"
        "    assert got == sorted(expected), (requested, got, expected)\n"
        "    db2 = TinyDB(tmp_path / 'db.json', storage=JSONStorage)\n"
        "    assert db2.count(where('int') == 9) == len(expected)\n"
        f"    assert db2.count(where('int') == 10) == ({0 if 1 in returned else 1})\n"
        f"    assert db2.count(where('int') == 20) == ({0 if 2 in returned else 1})\n"
        f"    assert db2.count(where('int') == 30) == ({0 if 3 in returned else 1})\n",
        params="tmp_path",
    )
    requested_r, _ = seed_mix(2)
    returned_r = _expect_returned(requested_r, existing)
    add_case(
        "test_sem_remove_survives_reload",
        "    db = TinyDB(tmp_path / 'db2.json', storage=JSONStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    requested = {requested_r!r}\n"
        f"    expected = {returned_r!r}\n"
        "    got = sorted(db.remove(doc_ids=requested))\n"
        "    assert got == sorted(expected), (requested, got, expected)\n"
        "    db2 = TinyDB(tmp_path / 'db2.json', storage=JSONStorage)\n"
        f"    assert len(db2) == 3 - len({returned_r!r})\n",
        params="tmp_path",
    )
    add_case(
        "test_sem_upsert_missing_inserts_and_persists",
        "    db = TinyDB(tmp_path / 'db3.json', storage=JSONStorage)\n"
        "    db.insert({'name': 'a'})\n"
        "    db.upsert(Document({'name': 'new', 'k': 1}, doc_id=99))\n"
        "    assert db.get(doc_id=99) == {'name': 'new', 'k': 1}\n"
        "    db2 = TinyDB(tmp_path / 'db3.json', storage=JSONStorage)\n"
        "    assert db2.get(doc_id=99) == {'name': 'new', 'k': 1}\n"
        "    assert len(db2) == 2\n",
        params="tmp_path",
    )

    # --- metamorphic: update/get agreement, idempotence, update-then-remove
    requested_m, _ = seed_mix(3)
    add_case(
        "test_sem_update_then_get_consistency",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        f"    requested = {requested_m!r}\n"
        "    updated = db.update({'int': 9}, doc_ids=requested)\n"
        "    got = sorted(db.get(doc_ids=requested), key=lambda doc: doc.doc_id)\n"
        "    want = sorted(db.get(doc_ids=updated), key=lambda doc: doc.doc_id)\n"
        "    assert got == want, (requested, updated, got, want)\n"
        "    assert db.count(where('int') == 9) == len(updated)\n",
    )
    add_case(
        "test_sem_update_idempotent",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        "    first = db.update({'int': 9}, doc_ids=[1, 99])\n"
        "    second = db.update({'int': 9}, doc_ids=[1, 99])\n"
        "    assert first == [1]\n"
        "    assert second == [1]\n"
        "    assert db.count(where('int') == 9) == 1\n"
        "    assert len(db) == 3\n",
    )
    add_case(
        "test_sem_update_then_remove_sequence",
        "    db = TinyDB(storage=MemoryStorage)\n"
        "    db.insert_multiple({'int': i * 10} for i in (1, 2, 3))\n"
        "    assert db.update({'int': 9}, doc_ids=[1, 99]) == [1]\n"
        "    assert sorted(db.remove(where('int') == 9)) == [1]\n"
        "    assert len(db) == 2\n"
        "    assert db.get(doc_id=1) is None\n",
    )

    text = _HEADER_DOCIDS.format(seed=seed) + "\n".join(lines) + "\n"
    return GeneratedSuite(
        filename="test_semantic_docids.py",
        text=text,
        expected_nodeids=sorted(expected),
    )


def _probe_for(arg: object) -> object:
    """A value guaranteed to be contained in *arg* for membership predicates."""
    if isinstance(arg, dict):
        return next(iter(cast(dict[str, object], arg)))
    if isinstance(arg, (list, tuple)):
        return cast(list[object], arg)[0]
    return arg


def generate_queries_suite(seed: int) -> GeneratedSuite:
    """Generate the tinydb-query-test-unhashable semantic suite (profile v1)."""
    rng = random.Random(seed)

    def random_container(depth: int = 0) -> object:
        if depth >= 3:
            return rng.choice([1, "x", 2.5, True, None])
        kinds = ["list", "dict", "tuple"] if depth == 0 else ["list", "dict", "tuple", "scalar"]
        kind = rng.choice(kinds)
        if kind == "list":
            return [random_container(depth + 1) for _ in range(rng.randint(1, 3))]
        if kind == "dict":
            return {
                f"k{rng.randint(0, 9)}": random_container(depth + 1)
                for _ in range(rng.randint(1, 3))
            }
        if kind == "tuple":
            return tuple(random_container(depth + 1) for _ in range(rng.randint(1, 3)))
        return rng.choice([1, "x", 2.5, True, None])

    lines: list[str] = []
    expected: list[str] = []

    def add_case(name: str, body: str) -> None:
        lines.append(f"def {name}():\n{body}\n")
        expected.append(_nodeid("test_semantic_queries.py", name))

    def nested_body(literal: str, probe: object) -> str:
        return (
            "    def _in_allowed(value, allowed):\n"
            "        return value in allowed\n"
            f"    arg = {literal}\n"
            f"    probe = {probe!r}\n"
            "    query = Query().val.test(_in_allowed, arg)\n"
            "    assert query({'val': probe}) is True\n"
            "    assert hash(query)\n"
            "    clone = Query().val.test(_in_allowed, arg)\n"
            "    assert hash(query) == hash(clone)\n"
        )

    # --- nested containers (the four known overfits fail these)
    nested_values: list[tuple[str, object]] = [
        ("list_of_dicts", [{"a": 1}, {"b": [2, 3]}]),
        ("dict_of_dicts", {"outer": {"inner": {"deep": [1, 2]}}}),
        ("tuple_with_list_and_dict", (1, [2, {"x": 3}])),
        ("deeply_nested_mixed", [{"k": (1, [2, {"j": 3}])}, [4, {"m": 5}]]),
    ]
    for name, value in nested_values:
        add_case(
            f"test_sem_nested_{name}",
            nested_body(repr(value), _probe_for(value)),
        )
    add_case(
        "test_sem_empty_containers",
        "    def _always(value, arg):\n"
        "        return True\n"
        "    for arg in ([], {}, ()):\n"
        "        query = Query().val.test(_always, arg)\n"
        "        assert query({'val': 1}) is True\n"
        "        assert hash(query)\n",
    )

    # --- randomized hidden argument shapes (seeded)
    random_args: list[object] = [random_container() for _ in range(8)]
    probes = [_probe_for(arg) for arg in random_args]
    add_case(
        "test_sem_randomized_args_hidden",
        "    def _in_allowed(value, allowed):\n"
        "        return value in allowed\n"
        f"    args = {random_args!r}\n"
        f"    probes = {probes!r}\n"
        "    for arg, probe in zip(args, probes):\n"
        "        query = Query().val.test(_in_allowed, arg)\n"
        "        assert query({'val': probe}) is True\n"
        "        assert hash(query)\n"
        "        clone = Query().val.test(_in_allowed, arg)\n"
        "        assert hash(query) == hash(clone)\n",
    )

    # --- metamorphic: equal args hash equal; distinct fixed args hash differently
    add_case(
        "test_sem_equal_args_equal_hash_many",
        "    def _in_allowed(value, allowed):\n"
        "        return value in allowed\n"
        f"    args = {random_args!r}\n"
        "    for arg in args:\n"
        "        q_a = Query().val.test(_in_allowed, arg)\n"
        "        q_b = Query().val.test(_in_allowed, arg)\n"
        "        assert hash(q_a) == hash(q_b)\n"
        "    q_list = Query().val.test(_in_allowed, [1, 2, 3])\n"
        "    q_dict = Query().val.test(_in_allowed, {'a': 1})\n"
        "    assert hash(q_list) != hash(q_dict)\n",
    )

    # --- differential: query result equals direct predicate application
    docs: list[dict[str, object]] = [
        {"val": rng.choice([1, 2, 3, "a", "b", None, 2.5, True])}
        for _ in range(rng.randint(6, 10))
    ]
    allowed: list[object] = [doc["val"] for doc in docs]
    expected_by_doc: list[bool] = [doc["val"] in allowed for doc in docs]
    add_case(
        "test_sem_differential_equivalence",
        "    def _in_allowed(value, allowed):\n"
        "        return value in allowed\n"
        f"    docs = {docs!r}\n"
        f"    allowed = {allowed!r}\n"
        f"    expected = {expected_by_doc!r}\n"
        "    query = Query().val.test(_in_allowed, allowed)\n"
        "    for doc, want in zip(docs, expected):\n"
        "        assert query(doc) == want, (doc, query(doc), want)\n",
    )

    # --- unfreezable custom object: matches, reports uncacheable, never raises
    add_case(
        "test_sem_unfreezable_matches_not_cacheable",
        "    class _Unhashable:\n"
        "        __hash__ = None\n"
        "    def _always(value, arg):\n"
        "        return isinstance(arg, _Unhashable)\n"
        "    query = Query().val.test(_always, _Unhashable())\n"
        "    assert query({'val': 1}) is True\n"
        "    assert query.is_cacheable() is False\n",
    )

    # --- hashable containers must stay cacheable and usable
    add_case(
        "test_sem_hashable_containers_cacheable",
        "    def _has(value, container):\n"
        "        return value in container\n"
        "    query = Query().val.test(_has, frozenset({1, 2, 3}))\n"
        "    assert query({'val': 1})\n"
        "    assert hash(query)\n"
        "    assert query.is_cacheable()\n"
        "    query_b = Query().val.test(_has, b'bytes')\n"
        "    assert hash(query_b)\n",
    )

    # --- multiple extra args (mixed shapes)
    add_case(
        "test_sem_multiple_extra_args",
        "    def _in_range(value, low, high, tags):\n"
        "        return low <= value <= high and value in tags\n"
        "    query = Query().val.test(_in_range, 1, 5, [1, 2, 3])\n"
        "    assert query({'val': 2})\n"
        "    assert not query({'val': 9})\n"
        "    assert hash(query)\n",
    )

    text = _HEADER_QUERIES.format(seed=seed) + "\n".join(lines) + "\n"
    return GeneratedSuite(
        filename="test_semantic_queries.py",
        text=text,
        expected_nodeids=sorted(expected),
    )
