"""HUD v6 deployment entry point for the application-v2 release (D-053/D-054).

Served by the deployment container via ``hud serve env_v2.py --host 0.0.0.0``
(``env_v2.py`` is a one-line re-export generated by the Dockerfile). It stages
the declared baseline into a fresh workspace before yielding the prompt and
grades the workspace state left by the agent through the shared frozen core,
exactly like the frozen ``env.py`` (Section 27.13), with one extension: the
``hardened_v2`` grader version dispatches to the semantic grader v2
(``grader_v2.grading.evaluator``).

Runner selection: inside the deployment container (``GRADER_AUDIT_IN_CONTAINER``)
grading runs as an isolated subprocess against the baked-in assets
(``InContainerRunner``, no Docker daemon, hardening §6/Q8); on a host
(local dev / tests) the Docker task images are used.
"""

from __future__ import annotations

import os
from collections.abc import AsyncGenerator, Mapping
from pathlib import Path

from hud.graders import EvaluationResult
from hud.environment import Workspace

from grader_audit.core.manifests import LoadedTask, discover_tasks
from grader_audit.core.workspace import WorkspaceManager
from grader_audit.images import resolve_task_image
from grader_v2.grading.runners import InContainerRunner
from grader_v2.hud.adapter import grade_workspace_async
from hud import Environment

_HERE = Path(__file__).resolve().parent
_IN_CONTAINER = os.environ.get("GRADER_AUDIT_IN_CONTAINER") == "1"

_DEFAULT_TASKS_DIR = "/app/tasks" if _IN_CONTAINER else str(_HERE.parents[1] / "tasks")
_TASKS_DIR = Path(os.environ.get("GRADER_AUDIT_TASKS_DIR", _DEFAULT_TASKS_DIR))


def _default_workspace_root() -> Path:
    if _IN_CONTAINER:
        return Path("/workspace")
    return _HERE.parents[1] / ".hud-workspace-v2"


_WORKSPACE_ROOT = Path(
    os.environ.get("GRADER_AUDIT_WORKSPACE_ROOT", str(_default_workspace_root()))
)

env = Environment(name="hud-grader-audit-v2", version="2.0.0")


class CapabilityDroppingWorkspace(Workspace):
    """Drop container setup capabilities before an agent command starts."""

    def bwrap_argv(
        self,
        command: list[str] | str,
        *,
        cwd: str | None = None,
        env: Mapping[str, str] | None = None,
        inherit_host_env: bool = True,
    ) -> list[str]:
        argv = super().bwrap_argv(
            command,
            cwd=cwd,
            env=env,
            inherit_host_env=inherit_host_env,
        )
        command_boundary = argv.index("--")
        argv[command_boundary:command_boundary] = ["--cap-drop", "ALL"]
        return argv


def _attach_workspace() -> Workspace:
    if not _IN_CONTAINER:
        return env.workspace(_WORKSPACE_ROOT, network=False, track_files=False)

    workspace = CapabilityDroppingWorkspace(
        _WORKSPACE_ROOT,
        network=False,
        track_files=False,
    )

    async def _start_workspace() -> None:
        await workspace.start()
        env.add_capability(workspace.capability("shell"))

    async def _stop_workspace() -> None:
        await workspace.stop()

    env.initialize(_start_workspace)
    env.shutdown(_stop_workspace)
    return workspace


_workspace = _attach_workspace()


def _task_registry() -> dict[str, object]:
    if not _TASKS_DIR.is_dir():
        return {}
    return {task.manifest.id: task for task in discover_tasks(_TASKS_DIR)}


_TASK_BY_ID = _task_registry()


def _resolve_task(task_id: str) -> LoadedTask:
    task = _TASK_BY_ID.get(task_id)
    if task is None or not isinstance(task, LoadedTask):
        known = ", ".join(sorted(_TASK_BY_ID)) or "(no tasks registered)"
        raise ValueError(f"unknown task_id {task_id!r}; registered tasks: {known}")
    return task


def _new_runner():
    if _IN_CONTAINER:
        return InContainerRunner()
    from grader_audit.core.docker_runner import DockerRunner

    return DockerRunner()


@env.template(
    id="grader_reliability_task",
    description="Bug-fix a fixture workspace; graded by the shared core (v2 deployment).",
)
async def grader_reliability_task(
    task_id: str, grader_version: str
) -> AsyncGenerator[str | EvaluationResult, str]:
    """Stage the baseline, prompt the agent, and grade the workspace state."""
    task = _resolve_task(task_id)
    manager = WorkspaceManager(task)
    workspace = manager.stage_fresh_root(_workspace.root)
    prompt_path = task.task_dir / "prompt.md"
    prompt = prompt_path.read_text(encoding="utf-8") if prompt_path.is_file() else ""
    _answer = yield prompt
    image = resolve_task_image(task)
    grade = await grade_workspace_async(
        task=task,
        grader_version=grader_version,
        workspace_root=_workspace.root,
        pristine_snapshot=workspace.pristine_snapshot,
        image=image,
        runner=_new_runner(),
    )
    yield grade.result
